services:
  - type: web
    name: domestic-animal-disease-detection
    runtime: static
    buildCommand: npm install --prefix react-app && npm run build --prefix react-app
    staticPublishPath: ./react-app/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
